version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: voxpopuli
      POSTGRES_USER: voxuser
      POSTGRES_PASSWORD: voxpass
    ports:
      - "8903:5432"
    volumes:
      #- ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
   # network_mode: host

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py seed_demo && python manage.py runserver 0.0.0.0:8902"
    volumes:
      - .:/app
    ports:
      - "8902:8902"
    environment:
      - DEBUG=1
      #- SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - PUBLIC_BACKEND_URL=http://10.191.221.67:8902
      - BIELIK_BASE_URL=${BIELIK_BASE_URL:-http://149.156.194.192:8080/v1}
      - BIELIK_API_KEY=${BIELIK_API_KEY}
      - BIELIK_MODEL=${BIELIK_MODEL:-SpeakLeash/bielik-11b-v3.0-instruct:Q4_K_M}
      - BIELIK_TIMEOUT=${BIELIK_TIMEOUT:-30}
      #- SECRET_KEY=django-insecure-twoj-klucz
     # - NEXT_PUBLIC_API_URL=http://149.156.194.192:8902
    depends_on:
      - db
    #network_mode: host

volumes:
  postgres_data:
