# Generated by Django 4.2.30 on 2026-07-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UwagaMapowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerokosc', models.FloatField(help_text='Latitude')),
                ('dlugosc', models.FloatField(help_text='Longitude')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('kategoria', models.CharField(max_length=100)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('oczekujaca', 'Oczekująca'), ('zatwierdzona', 'Zatwierdzona'), ('odrzucona', 'Odrzucona')], default='oczekujaca', max_length=20)),
                ('ankieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uwagi', to='surveys.ankieta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uwagi_mapowe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
