# Generated by Django 6.0.6 on 2026-06-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ankieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True)),
                ('kategoria', models.CharField(choices=[('transport', 'Transport'), ('zielen', 'Zieleń'), ('infrastruktura', 'Infrastruktura'), ('inne', 'Inne')], max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_rozpoczecia', models.DateTimeField(blank=True, null=True)),
                ('data_zakonczenia', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('szkic', 'Szkic'), ('aktywna', 'Aktywna'), ('zakonczona', 'Zakończona'), ('archiwalna', 'Archiwalna')], default='szkic', max_length=20)),
                ('widoczna_dla_gosci', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('typ', models.CharField(choices=[('jednokrotny', 'Jednokrotny wybór'), ('wielokrotny', 'Wielokrotny wybór'), ('skala', 'Skala'), ('tekst', 'Tekst')], max_length=20)),
                ('kolejnosc', models.IntegerField(default=0)),
                ('wymagane', models.BooleanField(default=False)),
                ('ankieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pytania', to='surveys.ankieta')),
            ],
            options={
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usera', models.IntegerField(blank=True, null=True)),
                ('tresc_odpowiedzi', models.TextField()),
                ('data_odpowiedzi', models.DateTimeField(auto_now_add=True)),
                ('adres_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='surveys.pytanie')),
            ],
        ),
    ]
