# Generated by Django 6.0.6 on 2026-07-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usera', models.IntegerField(blank=True, null=True)),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('sentyment', models.CharField(choices=[('pozytywny', 'Pozytywny'), ('neutralny', 'Neutralny'), ('negatywny', 'Negatywny')], default='neutralny', max_length=20)),
                ('wynik_sentymentu', models.FloatField(blank=True, null=True)),
                ('czy_oflagowany', models.BooleanField(default=False)),
                ('czy_usuniety', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'komentarz',
                'ordering': ['data_dodania'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usera', models.IntegerField(blank=True, null=True)),
                ('id_ankiety', models.IntegerField(blank=True, null=True)),
                ('tytul', models.CharField(max_length=255)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('czy_zablokowany', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'watek',
                'ordering': ['-data_utworzenia'],
                'managed': False,
            },
        ),
    ]
